/**
 * Created by jige on 2018/3/13.
 */
export const HASNOTCONFIGACTIONTYPE = 'HASNOTCONFIGACTIONTYPE'
export const SETRULEDATA_RULEMANAGE = 'SETRULEDATA_RULEMANAGE';
export const DELETERULEDATA_RULEMANAGE = 'DELETERULEDATA_RULEMANAGE';
export const SETRULECHECKED_RULEMANAGE = 'SETRULECHECKED_RULEMANAGE';


export const SETTASKDATASET_SIDEBAR = 'SETTASKDATASET_SIDEBAR';


export const SET_STATE_TAG = 'SET_STATE_TAG';
export const SET_CURRENTRECORD_TAG = 'SET_CURRENTRECORD_TAG';
export const SET_LINEDATA_TAG = 'SET_LINEDATA_TAG';


export const SET_SHOW_TAB_TYPE_RULEMANAGE = 'SET_SHOW_TAB_TYPE_RULEMANAGE';
export const SET_RULE_DATA_RULEMANAGE = 'SET_RULE_DATA_RULEMANAGE';


export const SETDICTIONAEYDATA_RULEMANAGE = 'SETDICTIONAEYDATA_RULEMANAGE';
export const ADDDICTIONAEYDATA_RULEMANAGE = 'ADDDICTIONAEYDATA_RULEMANAGE';
export const UPDATEDICTIONAEYDATA_RULEMANAGE = 'UPDATEDICTIONAEYDATA_RULEMANAGE';
export const DELETEDICTIONAEYDATA_RULEMANAGE = 'DELETEDICTIONAEYDATA_RULEMANAGE';
export const CLEARDICTIONAEYDATA_RULEMANAGE = 'CLEARDICTIONAEYDATA_RULEMANAGE';
export const SETSHOWCONTENT_RULEMANAGE = 'SETSHOWCONTENT_RULEMANAGE';


export const TOGGLE_TASK = 'TOGGLE_TASK';
export const SETUSERDATALIST_TASK = 'SETUSERDATALIST_TASK';
export const SETUSERLIST_TASK = 'SETUSERLIST_TASK';
